name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install premake5 
      run: sudo wget https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-linux.tar.gz && tar -xvzf ./premake-5.0.0-beta2-linux.tar.gz
    - name: run premake5
      run: ./premake5 gmake2
    - name: make (default to debug)
      run: make
